#!/bin/bash
FILEURL=https://data.caida.org/datasets/passive-2016/equinix-chicago/20160121-130000.UTC/equinix-chicago.dirA.20160121-125911.UTC.anon.pcap.gz

USERPASS=dfoucard@inet.tu-berlin.de:Wr3-cSJ-6ps-YRp

curl -u $USERPASS $FILEURL > data.pcap.gz

#data needs to be made human-readable (takes time)
gunzip -fk data.pcap.gz
sudo tcpdump -q -n -t -r data.pcap | grep IP | sed 's/\./ /g' | awk '{print $2" "$3" "$4" "$5"\t"$8" "$9" "$10" "$11}' | grep -v "[a-z:]" > trace 2> /dev/null

# saving space - optional
# rm data.pcap.gz
# rm data.pcap
